`ffmpeg-drc-file`: use `libfdk_aac` and fix podcast downloads

diff --git a/bin/ffmpeg-dynamic-range-compress-file b/bin/ffmpeg-dynamic-range-compress-file
--- a/bin/ffmpeg-dynamic-range-compress-file
+++ b/bin/ffmpeg-dynamic-range-compress-file
@@ -11,33 +11,124 @@ shopt -s inherit_errexit  # Bash disables set -e in command substitution by defa
 # used in trap
 exit_code=1
 
-in="$1"
-out_unset=""
-shift
-if [ $# -lt 2 ]; then
-  tmpdir="$(mktemp -d)"
-  echo "[.] using $tmpdir for $(basename "$in")"  >&2
-  cleanup () {
-    rm -r "$tmpdir"
-    exit "$exit_code"
-  }
-  trap cleanup EXIT
+aac=(-c:a aac)
 
-  out="$tmpdir/$(basename "$in")"
-  out_unset="true"
+_help() {
+cat <<EOF
+USAGE: $(basename $0) [FLAGS] [OPTIONS] IN [OUT]
+
+FLAGS:
+  --remote-input        Will copy IN to the temp file to speed up processing (e.g. if the file lives on NFS)
+OPTIONS:
+  --vbr                 Variable bitrate (libfdk_aac only)
+                        https://trac.ffmpeg.org/wiki/Encode/AAC
+  -t|--threads NUM      Number of ffmpeg threads [default: num of physical cpus]
+  --min-db-level NUM    Minimum decibel level [default: 45]
+EOF
+}
+
+
+if [ "$(uname)" != Darwin ]; then
+  NUM_THREADS="$(grep cores /proc/cpuinfo | head -n1 | awk 'NR==1 { print $4; exit }')"
 else
-  out="$2"
+  NUM_THREADS="$(sysctl -n hw.ncpu)"
+fi
+REMOTE_INPUT=''
+MIN_DB_LEVEL=45
+while [ $# -gt 0 ]; do
+key="$1"
+  case "$key" in
+    --remote-input)
+    REMOTE_INPUT=true
+    shift
+    ;;
+
+    --min-db-level)
+    MIN_DB_LEVEL="$2"
+    shift 2
+    ;;
+
+    --vbr)
+    if ffmpeg -buildconf | grep libfdk; then
+      libfdk_aac=(-c:a libfdk_aac -vbr "$2")
+      aac=("${libfdk_aac[@]}")
+      echo '[.] using libfdk_aac' >&2
+    else
+      echo '[.]  libfdk_aac not found' >&2
+      exit 2
+    fi
+    shift 2
+    ;;
+
+    -t|--threads)
+    NUM_THREADS="$2"
+    shift 2
+    ;;
+
+    -h|--help)
+    _help
+    exit 0
+    ;;
+
+    --)
+    shift
+    break
+    ;;
+
+    *)
+    break
+    ;;
+
+  esac
+done
+echo "[.] using $NUM_THREADS threads."  >&2
+
+if [ $# -gt 1 ]; then
+  in="$1"
+  OUT="$2"
+  OUT_TEMPORARY=''
+  shift 2
+else
+  in="$1"
+  OUT=''
+  OUT_TEMPORARY='true'
   shift
 fi
 
-# set to val of third arg or `45`
-min_db_level="${3:-45}"
 
-codec=(-c:a aac)
+tmpdir="$(mktemp -d)"
+echo "[.] temp dir: $tmpdir"  >&2
+cleanup () {
+  set +x
+  rm -r "$tmpdir"
+  exit "$exit_code"
+}
+trap cleanup EXIT
+
+
+if [ -z "$OUT" ]; then
+  OUT="$tmpdir/$(basename "$in" | sed -r 's#(.*)\.[^\.]+$#\1.m4a#')"
+  echo "[.] out file temporary: $OUT"  >&2
+else
+  out_dir="$(dirname "$(realpath "$OUT")")"
+  if [ ! -d "$out_dir" ]; then
+    out_dir="$(realpath "$PWD")"
+  fi
+  echo "[.] out explicitly set: ${out_dir}/$(basename "$OUT")"  >&2
+fi
+
+if [ -n "$REMOTE_INPUT" ]; then
+  TMP_IN="$tmpdir/in_prefix-$(basename "$in")"
+  REAL_IN="$in"
+  cp "$in" "$TMP_IN"
+  in="$TMP_IN"
+fi
+
+
 
 
 # ATTENTION: strips video (-vn)
-if ffmpeg -i "$in" -y -vn "${codec[@]}" -filter_complex "compand=attacks=0:points=-$min_db_level/-900|-$(( min_db_level - 5 ))/-10|-5/-10|0/-10:gain=3" "$out" "$@"  >"$tmpdir"/stdout 2>"$tmpdir"/stderr; then
+if ffmpeg -i "$in" -y -vn "${aac[@]}" -filter_complex "compand=attacks=0:points=-$MIN_DB_LEVEL/-900|-$(( MIN_DB_LEVEL - 5 ))/-10|-5/-10|0/-10:gain=3" "$@" "$OUT"  >"$tmpdir"/stdout 2>"$tmpdir"/stderr; then
   echo "[.] $in: success"  >&2
   exit_code=0
 else
@@ -47,6 +138,14 @@ else
   exit "$exit_code"
 fi
 
-if [ -n "$out_unset" ]; then
-  mv "$out" "$in"
+if [ -n "$OUT_TEMPORARY" ]; then
+  if [ -n "$REMOTE_INPUT" ]; then
+    set -x
+    mv "$OUT" "$REAL_IN"
+    set +x
+  else
+    set -x
+    mv "$OUT" "$in"
+    set +x
+  fi
 fi
