Add `ab-av1-libx265-file`

diff --git a/bin/ffmpeg-dynamic-range-compress-file b/bin/ffmpeg-dynamic-range-compress-file
--- a/bin/ffmpeg-dynamic-range-compress-file
+++ b/bin/ffmpeg-dynamic-range-compress-file
@@ -39,7 +39,9 @@ if ffmpeg -i "$in" "${codec[@]}" -filter_complex "compand=attacks=0:points=-$min
   echo "[.] $in: success"  >&2
   exit_code=0
 else
-  echo "[!] $in: failure"  >&2
+  exit_code="$?"
+  echo "[!] $in: failure. exit_code: $exit_code"  >&2
+  tail "$tmpdir"/std* >&2
   exit "$exit_code"
 fi
 
diff --git a/bin/ffmpeg-reencode-libx265-file b/bin/ffmpeg-reencode-libx265-file
--- a/bin/ffmpeg-reencode-libx265-file
+++ b/bin/ffmpeg-reencode-libx265-file
@@ -124,7 +124,9 @@ if ffmpeg -threads "$NUM_THREADS" -i "$in" -crf "$CRF" -map 0:v -map 0:a -c:v "$
   echo "[.] $in: success"  >&2
   exit_code=0
 else
-  echo "[!] $in: failure"  >&2
+  exit_code="$?"
+  echo "[!] $in: failure. exit_code: $exit_code"  >&2
+  tail "$tmpdir"/std* >&2
   exit "$exit_code"
 fi
 
