cleanup

diff --git a/bin/git b/bin/git
--- a/bin/git
+++ b/bin/git
@@ -1,12 +1,21 @@
 #!/usr/bin/env bash
 
-set -x
+# all of these stem from https://www.shellcheck.net/wiki/
+set -o pipefail  # propagate errors
+set -u  # exit on undefined
+set -e  # exit on non-zero return value
+#set -f  # disable globbing/filename expansion
+shopt -s failglob  # error on unexpaned globs
+shopt -s inherit_errexit  # Bash disables set -e in command substitution by default; reverse this behavior
+
+
 if [ "$1" = push ]; then
   if git-remote-gcrypt --check "$(grep url .git/config  | awk '{ print $3 }')" >/dev/null 2>&1; then
+    # shellcheck disable=SC2016
+    echo '[.] running pull for `git-remote-gcrypt` repo' >&2
     git pull
   fi
 fi
-set +x
 
 if [ "$(uname)" = Darwin ]; then
   command=(/usr/local/bin/git)
