Generalize kubectl plugins (to not only use oc but kubectl also)

diff --git a/kubernetes/bin/kubectl-delete_namespace_finalizer b/kubernetes/bin/kubectl-delete_namespace_finalizer
--- a/kubernetes/bin/kubectl-delete_namespace_finalizer
+++ b/kubernetes/bin/kubectl-delete_namespace_finalizer
@@ -1,14 +1,29 @@
 #!/usr/bin/env bash
 
+
+if which kubectl >/dev/null; then
+  binary=kubectl
+elif which oc >/dev/null; then
+  binary=oc
+else
+  echo -e "${RED}Missing kubectl and oc binaries!\nPlugin needs at least one.$NC" >&2
+  exit 1
+fi
+
+
 namespace="$1"
 finalizer_to_remove="${2:-kubernetes}"
 tmp_dir="$(mktemp -d)"
 filename="$tmp_dir/$namespace".yaml
 
-trap "kill %%  2>/dev/null; rm -rf $tmp_dir" EXIT
+cleanup () {
+  kill %%  2>/dev/null
+  rm -rf "$tmp_dir"
+}
+trap cleanup EXIT
 
-kubectl proxy &
-kubectl get namespace "$namespace" -o yaml > "$filename"
+"$binary" proxy &
+"$binary" get namespace "$namespace" -o yaml > "$filename"
 
 sed -i "/- $finalizer_to_remove/d"  "$filename"
 
diff --git a/kubernetes/bin/kubectl-get_all_namespaced_resources b/kubernetes/bin/kubectl-get_all_namespaced_resources
--- a/kubernetes/bin/kubectl-get_all_namespaced_resources
+++ b/kubernetes/bin/kubectl-get_all_namespaced_resources
@@ -6,10 +6,17 @@ set -e  # exit on non-zero return value
 #set -f  # disable globbing/filename expansion
 shopt -s failglob  # error on unexpaned globs
 
+if which kubectl >/dev/null; then
+  binary=kubectl
+elif which oc >/dev/null; then
+  binary=oc
+else
+  echo -e "${RED}Missing kubectl and oc binaries!\nPlugin needs at least one.$NC" >&2
+  exit 1
+fi
 
 # Parse arguments
 positional_args=()
-NAMESPACE=''
 while [ $# -gt 0 ]; do
 key="$1"
   case "$key" in
@@ -27,6 +34,5 @@ key="$1"
 done
 set -- "${positional_args[@]}"
 
-oc api-resources --verbs=list --namespaced -o name \
-  | xargs -n 1 oc get "$@" --show-kind --ignore-not-found
-
+"$binary" api-resources --verbs=list --namespaced -o name \
+  | xargs -n 1 "$binary" get "$@" --show-kind --ignore-not-found
diff --git a/kubernetes/bin/kubectl-watch_namespace b/kubernetes/bin/kubectl-watch_namespace
--- a/kubernetes/bin/kubectl-watch_namespace
+++ b/kubernetes/bin/kubectl-watch_namespace
@@ -13,6 +13,14 @@ set -e  # exit on non-zero return value
 #set -f  # disable globbing/filename expansion
 shopt -s failglob  # error on unexpaned globs
 
+if which kubectl >/dev/null; then
+  binary=kubectl
+elif which oc >/dev/null; then
+  binary=oc
+else
+  echo -e "${RED}Missing kubectl and oc binaries!\nPlugin needs at least one.$NC" >&2
+  exit 1
+fi
 
 put_args () {
   for item in "$@"; do
@@ -82,7 +90,7 @@ _split_and_run_tmux_command () {
 
   tmux send-keys -t "$pane_id" "source ~/.bashrc; \
     set-kubecontext '$region'; \
-    watch oc get pod -n '$namespace' " \
+    watch "$binary" get pod -n '$namespace' " \
     "$(put_args "${positional_args[@]}")" C-m
   }
 
