Generalize `limactl restart` command

diff --git a/bin/darwin/limactl b/bin/darwin/limactl
--- a/bin/darwin/limactl
+++ b/bin/darwin/limactl
@@ -27,23 +27,24 @@ key="$1"
     ;;
 
     restart)
-      if [ default = "$2" ]; then
-        /opt/homebrew/bin/limactl stop default  || true  # ignore failure -> instance might be stopped already
-        /opt/homebrew/bin/limactl start default
-      fi
-      shift 2
+      shift
+      set -x
+      /opt/homebrew/bin/limactl stop "$@"  || true  # ignore failure -> instance might be stopped already
+      /opt/homebrew/bin/limactl start "$@"
+      set +x
 
-      break
+      exit
+      # break
+
       ;;
 
     --|*)
-    set -x
-    /opt/homebrew/bin/limactl "$@"
-    set +x
-
     break
     ;;
 
   esac
 done
 
+
+set -x
+/opt/homebrew/bin/limactl "$@"
